name: Docker Publish Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  call-reusable-workflow:
    uses: JourneyDocker/github-workflows/.github/workflows/docker-publish.yml@main
    with:
      tag: main
      platforms: linux/amd64
    secrets: inherit
