name: Docker Publish Latest

on:
  push:
    tags:
    - '*'

permissions:
  packages: write

jobs:
  call-reusable-workflow:
    uses: JourneyDocker/github-workflows/.github/workflows/docker-publish.yml@main
    with:
      tag: latest
      platforms: linux/amd64
    secrets: inherit
